spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mirea_dates
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
          max-file-size: 5MB
          max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
  cache:
    type: redis
    redis:
      time-to-live: 1h
file:
  upload-dir: uploads/
server:
  ssl:
    enabled: true
  port: 443
  address: 0.0.0.0